### ISSUE TITLE
A note about the PHP session and the recommended Redis session

### ISSUE THREAD

**Issue by adulau** [MISP/misp-book#36]
A note about the PHP session and the recommended Redis session and the config
aspect too:

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-redis-server-as-a-session-handler-for-php-on-ubuntu-14-04

**Comment by koenigswinter** [comment]
Hi! Thanks for the good tutorial reference. Session handling via Redis works fine on my instance :+1: . Did you also manage to get the redis authentication to work? I tried the following settings (Ubuntu 16.04.1):

1) /etc/redis/redis.conf
`requirepass <mySuperSecretPassword>`
2) /etc/php/7.0/apache2/php.ini
```
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379?auth=<mySuperSecretPassword>"
```
3) MISP Server Settings
```
Plugin settings --> ZeroMQ
Plugin.ZeroMQ_redis_host => 127.0.0.1
Plugin.ZeroMQ_redis_port => 6379
Plugin.ZeroMQ_redis_password => <mySuperSecretPassword>
Plugin.ZeroMQ_redis_database => 1
Plugin.ZeroMQ_redis_namespace => mispq
```

However, after restarting Apache & Redis, I can't access https://misp.example.com/servers/serverSettings/ anymore and receive the following error in /var/www/MISP/app/tmp/logs/error.log:

```
2017-01-12 14:35:40 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 126]
Trace:
ResqueStatus\ResqueStatus::getWorkers() - APP/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 126
Server::workerDiagnostics() - APP/Model/Server.php, line 2869
ServersController::serverSettings() - APP/Controller/ServersController.php, line 750
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2017-01-12 14:35:40 Error: [RedisException] Failed to AUTH connection
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(153): Redis->lLen('queue:cache')
#1 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(342): Resque::size('cache')
#2 /var/www/MISP/app/Model/Server.php(2902): CakeResque::getQueueSize('cache')
#3 /var/www/MISP/app/Controller/ServersController.php(750): Server->workerDiagnostics(0)
#4 [internal function]: ServersController->serverSettings()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```
Do you have to set the Redis password anywhere else? Cheers

**Comment by 4ekin** [comment]
File app/Plugin/CakeResque/Config/config.php
$config['CakeResque'] = array(
        'Redis' => array(
                'host' => 'localhost',          // Redis server hostname
                'port' => 6379,                         // Redis server port
                'database' => 0,                        // Redis database number
                'namespace' => 'resque',        // Redis keys namespace
                'password' => null        // Redis password
        ),

After change 'password' to mysecretpass, it fix problem
